PortalAcraiz/urls.py
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA


urlpatterns += staticfiles_urlpatterns()

lcr/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from lcr.views import LcrView

urlpatterns = patterns('',
    url(r'^', LcrView.as_view()),
)

certificados/models.py
# -*- coding: utf-8 -*-
# import Django
import os
from django.db import models

# import project packages
from core.models import NombreAbstract
from secciones.models import Categorias

# pre_save
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

#from subprocess import call
import subprocess

# Librerías y funciones 
from lib.funciones import check_algoritmo, check_fecha

class Proveedores(models.Model):
    '''
    Modelo para definir los datos de un PSC
    '''
    nombre = models.CharField(max_length= 100, verbose_name=u"Nombre del PSC")
    acronimo = models.CharField(max_length=100, verbose_name=u"Acrónimo del proveedor",
    help_text=u" Este acrónimo se usará para generar la ruta de los documentos para este proveedor. <br/> Ej: Super Intendencia de Cervicios de Certificación Electrónica. Acrónimo: SUSCERTE."
    )
    publicar = models.BooleanField(default=False,
            verbose_name=u'Publicar datos del proveedor', help_text=u"Publicar o despublicar DPC's/PC's, Certificados, Lcr, etc. de todas las AC's de este proveedor")
    logo = models.FileField(upload_to = 'LOGOS', blank=True)


    class Meta:
        verbose_name = u'proveedor'
        verbose_name_plural = u'proveedores'

    def __unicode__(self):
        return u'%s' % (self.nombre)

@receiver(pre_save, sender=Proveedores)
def pre_acronimo(sender, instance, **kwargs):
    acroniom_mayus = instance.acronimo.upper().replace(' ', '')
    instance.acronimo = acroniom_mayus


class AutoridadesCertificadoras(models.Model):
    categoria = models.ForeignKey(Categorias)
    nombre = models.CharField(max_length=100,
            verbose_name=u'Nombre de la AC')
    proveedor = models.ForeignKey(Proveedores, 
                )
    publicar = models.BooleanField(default=False,
            verbose_name=u'Publicar datos de la AC', help_text=u"Publicar o despublicar TODOS los datos de esta Autoridad de Certificación.")
    publicar_dpc = models.BooleanField(default=False,
            verbose_name=u'Publicar DPC', help_text=u"Publicar o despublicar DPC para esta Autoridad de Certificación.")


    class Meta:
        verbose_name = u'Autoridad Certificadora'
        verbose_name_plural = u'Autoridades Certificadoras (AC)'

    def __unicode__(self):
        return '%s' % (self.nombre)


class TipoFormato(NombreAbstract):
    '''
    Lista de Formatos de documentos disponibles
    '''

    class Meta:
        verbose_name = u'Tipo de formato'
        verbose_name_plural = u'Tipos de formatos'


class StatusCertificados(NombreAbstract):
    '''
    Lista de estatus de vaildez de un certificado
    '''

    class Meta:
        verbose_name = u'Status'
        verbose_name_plural = 'Status'


class CertificadoAbstract(models.Model):
    '''
    Datos de un certificado
    '''

    ac = models.ForeignKey(AutoridadesCertificadoras,
            verbose_name=u'AC',
            help_text=u'AC propietaria del documento')
    algoritmo = models.CharField( max_length=10, verbose_name=u'algoritmo de certificado',
            help_text=u'Algoritmo de cifrado del documento', blank=True)
    fecha_inicio = models.DateField(verbose_name=u'fecha de generación',
            help_text=u'Fecha de generación del documento', blank=True, null=True)
    fecha_fin = models.DateField(verbose_name=u'fecha de vencimiento',
            help_text=u'Fecha de vencimiento del documento', blank=True, null=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return u'%s %s %s' % (self.ac, self.fecha_inicio, self.etiqueta)

    def __unicode__(self):
        return u'%s (%s)' % (self.ac, self.algoritmo)

    def get_formatos(self):
        import pdb
        #pdb.set_trace()
        formatos = []
        formato_cert = FormatoCert.objects.filter(formato=self)
        [formatos.append(v.__unicode__()) for v in formato_cert]
        return formatos


class Certificados(CertificadoAbstract):
    etiqueta = models.CharField(max_length=1000,
            verbose_name=u'Nombre del documeto',
            help_text=u'Etiqueta del documento. Ej: Certificado de Persona Natural')
    status = models.ForeignKey(StatusCertificados,
            verbose_name=u'Status',
            help_text=u'estatus de este certificado')

    publicar = models.BooleanField(default=False,
            verbose_name=u'Publicar PC', help_text=u"Publicar o despublicar todas las PC's vinculadas a este certificado")

    class Meta:
        verbose_name = u'certificado'
        verbose_name_plural = 'certificados'



class FormatoCert(models.Model):
    ''' Diferentes formatos disponibles para cada certificado '''

    def get_image_path(self, filename):
        
        autoridad = (self.certificado.ac.proveedor.acronimo)
        ruta = 'CERTIFICADOS/%s' % (autoridad)
        #print ruta
        return os.path.join( ruta, filename)

    certificado = models.ForeignKey(Certificados)
    formato = models.ForeignKey(TipoFormato,
            verbose_name=u'Formato',
            help_text=u'Formato que en el que se publicará certificado')

    archivo = models.FileField(upload_to = get_image_path)
    huella = models.FileField(upload_to = get_image_path)

    class Meta:
        verbose_name = u'Formatos de Certificado'
        verbose_name_plural = u'Formatos de Certificado'

    def get_formatos(self):
        formatos = []
        formato_cert = FormatoCert.objects.filter(formato=self)
        [formatos.append(v.__unicode__()) for v in formato_cert]
        return formatos

    def __unicode__(self):
        return '%s' % (self.formato)

@receiver(post_save, sender=FormatoCert)
def post_handler(sender, instance, **kwargs):
    # Actualizo el algoritmo
    archivo_nombre = str(instance.archivo)
    ruta = 'media/'+archivo_nombre

    if archivo_nombre.__contains__('.txt'):
        instance.certificado.algoritmo = check_algoritmo(ruta)
        instance.certificado.fecha_inicio = check_fecha(ruta,"Not Before: ")
        instance.certificado.fecha_fin = check_fecha(ruta,"Not After : ")
        instance.certificado.save(update_fields=["fecha_inicio"])
        instance.certificado.save(update_fields=["fecha_fin"])
        instance.certificado.save(update_fields=["algoritmo"])

    

lcr/models.py
# -*- coding: utf-8 -*-
# import Django
import os
from django.db import models

# import project packages
from core.models import NombreAbstract
from certificados.models import TipoFormato, CertificadoAbstract


# pre_save
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

#from subprocess import call
import subprocess

# Librerías y funciones 
from lib.funciones import check_algoritmo, check_fecha

class TipoFormato(NombreAbstract):
    '''
    Modelo para definir el tipo de formato
    '''

    class Meta:
        verbose_name = u'Tipo de formato'
        verbose_name_plural = u'Tipos de formatos'


class TipoCert(NombreAbstract):
    '''
    Modelo para definir el tipo de LCR
    '''

    class Meta:
        verbose_name = u'Tipo de LCR'   
        verbose_name_plural = u'Tipos de LCR'


class Lcr(CertificadoAbstract):
    '''
    Datos de una LCR
    '''
    publicar = models.BooleanField(default=True,
            verbose_name=u'¿Publicar LCR?',
            help_text=u'¿Desea que se publiquen LCRs para esta AC?')
    class Meta:
        verbose_name = u'LCR'
        verbose_name_plural = 'LCR'


class FormatoLcr(models.Model):
    '''Diferentes formatos para cada LCR'''
    def get_image_path(self, filename):
        autoridad = (self.lcr.ac.proveedor.acronimo)
        ruta = 'LCR/%s' % (autoridad)
        return os.path.join( ruta, filename)

    lcr = models.ForeignKey(Lcr, verbose_name='LCR')
    formato = models.ForeignKey(TipoFormato,
            verbose_name=u'Formato',
            help_text=u'Formato que en el que se publicará la LCR',
            related_name='Formatos de la LCR')
    archivo = models.FileField(upload_to = get_image_path,
            blank=True,
            help_text=u'Cargue el archivo de la LCR correspondiente')
    huella = models.FileField(upload_to = 'LCR/HUELLA')

    class Meta:
        verbose_name = u'Formatos de la LCR'
        verbose_name_plural = u'Formatos de LCR'

    def __unicode__(self):
        return '%s' % (self.lcr)

@receiver(pre_save, sender=FormatoLcr)
def pre_handler(sender, instance, **kwargs):
    '''
    Esto está para que pongas la función de borrado y actualización de la que hablamos
    '''
    #print "Ruta antes"
    #ruta = "media/"+str(instance.archivo)
    #print ruta


@receiver(post_save, sender=FormatoLcr)
def post_handler(sender, instance, **kwargs):

    archivo_nombre = str(instance.archivo)
    ruta = 'media/'+archivo_nombre

    if archivo_nombre.__contains__('.txt'):
        instance.lcr.algoritmo = check_algoritmo(ruta)
        instance.lcr.fecha_inicio = check_fecha(ruta,"Last Update: ")
        instance.lcr.fecha_fin = check_fecha(ruta,"Next Update: ")
        instance.lcr.save(update_fields=["fecha_inicio"])
        instance.lcr.save(update_fields=["fecha_fin"])
        instance.lcr.save(update_fields=["algoritmo"])




    # Para hacer la actualización automática del OPSC
    ruta_origen = "media/"+str(instance.archivo)
    # Se actualiza el OCSP automáticamente
    ruta_destino = "media/OCSP/"
    os.system("rsync "+ruta_origen+" "+ruta_destino)

lcr/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, HttpResponse
from django.views.generic.base import View, TemplateView
from certificados.models import AutoridadesCertificadoras
from lcr.models import Lcr, FormatoLcr

class LcrView(View):
    template = 'acraiz/lcr.html'
    diccionario = {}

    def get(self, request, *args, **kwargs):
        autoridades = AutoridadesCertificadoras.objects.all()
        self.diccionario.update({'autoridades': autoridades})

        return render(request, 
            template_name = self.template,
            dictionary = self.diccionario,
        )

PortalAcraiz/templates/acraiz/acraiz.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block contenido %}
   <div id="interna"> <!-- InstanceBeginEditable name="contenido_segmentado" -->
      <div class="informativa">
        <div id="contenedorInformacion">
 {% placeholder noticias %}




      </div></div>
      <!-- InstanceEndEditable --> </div>

{% endblock contenido %}

PortalAcraiz/templates/acraiz/certificado_valido.html
{% extends "base.html" %}
{% load cms_tags %}
{% block title %}{% page_attribute 'title' %}{% endblock title %}
{% block contenido %}

{% for categoria in categorias %}
<!--========== Otra sección ========-->
<div class="container">
  {% ifequal categoria.publicar_cat True %}
  <header class="clearfix">
    <h3 class="titulo_categoria">{{ categoria }}</h3>
  </header>
<div class="caja">
  {% for autoridad in categoria.autoridadescertificadoras_set.get_query_set %}
    <div class="main container">
      <ul id="rb-grid" class="rb-grid clearfix">
      <!--========== Otro Cuadro ========-->
        {% ifequal autoridad.proveedor.publicar True %}
        {% ifequal autoridad.publicar True %}
        <header class="clearfix">
          <h3 class="titulo-2"  style=" padding-bottom: 5px; border-bottom: 1px solid #DDD;">{{ autoridad.nombre }}</h3>
        </header>
          
          {% for certificado in autoridad.certificados_set.get_query_set %}
            {% ifequal certificado.status.nombre "Válido" %}
              {% if certificado.fecha_fin >= fecha_actual %}
                <li>
                  <i class="fa fa-cloud-download icono-cuadro-princ"></i>
                  <h3>{{ certificado.etiqueta }}</h3>
                  <span class="rb-temp">{{ certificado.hash_cert }}</span>
                  <div class="rb-overlay">
                    <span class="rb-close"><i class="fa fa-close"></i></span>
                    <div class="rb-week">
                      <div>
                        <span class="rb-city span-overbox-header">{{ certificado.etiqueta }}</span>
                        <i class="span-overbox-icon fa fa-cloud-download"></i>
                        <span class="span-overbox-footer">{{ certificado.hash_cert }}</span>
                        <p><a class="boton boton-historico showMenu current-demo" data-id="{{ certificado.ac.id }}" href="secciones/historicos/"><i class='fa fa-plus fa-3x'></i>  Históricos </button></a>
                      </div>

                      {% for formato in certificado.formatocert_set.get_query_set %}
                      <div class="span-columna">
                        <span class="descarga-formato">
                        <span class="header-colum-formato-overbox">{{ formato.formato }}</span>
                        <a href="/media/{{ formato.archivo }}" class="enlacelist"
                          onclick="window.open(this.href, '', 'resizable=yes,status=no,location=no,toolbar=no,menubar=no,fullscreen=no,scrollbars=yes,dependent=no,width=700,height=500'); return false;">
                          <i class="fa fa-download fa-5x span-columna-icon"></i>
                        </a>
                        </span>





                        <a href="{{ formato.huella }}" class="enlacelist" 
                          onclick="window.open(this.href, '', 'resizable=yes,status=no,location=no,toolbar=no,menubar=no,fullscreen=no,scrollbars=yes,dependent=no,width=700,height=500'); return false;">
                          <span class="span-columna-footer">Huella SHA1</span>
                        </a>
                      </div>
                      {% endfor %}
                      </div>
                </li>
                {% endif %}
            {% endifequal %}
          {% endfor %}
          {% endifequal %}
        {% endifequal %}
      </ul>
    </div><!-- /.main-->
  {% endfor %}
  </div>
  <br>
  {% endifequal %}
</div><!-- /.container -->
{% endfor %}



{% endblock %}
{% block historicos %}
{% endblock %}
{% block javascript %}
<script>
    $('.boton-historico').on('click', consulta_cert);
    function consulta_cert() {
    // Acá se pasa el ID para el historico
        var id = $(this).attr("data-id");
        console.log(id);
        $.ajax({
          type: 'GET',
          data:{'id':id},
          url: '/es-ve/certificados-validos/',
          success: function(data) {
            console.log(data);
        /*     var html=''+
    '<article id="panel-redecho" class="panel-derecho scroll-pane">'+
    '<section id="cd-timeline" class="cd-container">';
              for (var i = 0; i < data.length; i++) {
                html += '<div class="cd-timeline-block">';
                  //Cambio de color de cd-timeline-img
                  /*if(data[i].fields.status.fields.status == "Válido"){
                    html+='<div class="cd-timeline-img cd-picture" >';
                  }
                  if(data[i].fields.status.fields.status == "Suspendido"){
                    html+='<div class="cd-timeline-img cd-location" >';
                  }
                  if(data[i].fields.status.fields.status == "Revocado"){
                    html+='<div class="cd-timeline-img cd-movie" >';
                  }* /
                  html+='<div class="cd-timeline-img cd-picture" >';
                  html+=''+
                    '<i class="fa fa-file-text icono-timeline"></i>'+
                  '</div> <!-- cd-timeline-img -->'+
                  '<div class="cd-timeline-content">'+
                    '<span id="titul" style="display:inline; font: 22px/1rem Montserrat; margin-left:1rem; ">'+data[i].fields.ac.fields.nombre+'</span>'+
                    '<span" >Status: '+data[i].fields.status.fields.nombre+'</span>'+
                    '<span style="float:right; margin-right:1.5rem;" >Hash: '+data[i].fields.hash_cert.fields.nombre+'</span>'+
                    //''+data[i].extras.get_formatos+
                      '<table >'+
                        '<thead>'+
                          '<tr>'+
                            '<th>Base 64</th><th>Texto</th><th>PEM</th><th>DER</th>'+
                          '</tr>'+
                        '</thead>'+
                        '<tbody>'+
                          '<tr>'+
                            '<td>Descargar</td><td>Descargar</td><td>Descargar</td><td>Descargar</td>'+
                          '</tr><tr>'+
                            '<td>Huella SHA1</td><td>Huella SHA1</td><td>Huella SHA1</td><td>Huella SHA1</td>'+
                          '</tr>'+
                        '</tbody>'+
                      '</table>'+
                      /*'<span class="cd-date">fecha</span>'+* /
                    '<span class="cd-date">'+ConvierteFechaENaES(data[i].fields.fecha_inicio)+'</span>'+
                    '<span class="cd-date" style="margin-top:22px;">'+ConvierteFechaENaES(data[i].fields.fecha_fin)+'</span>'+
                  '</div> <!-- cd-timeline-content -->'+
                '</div> <!-- cd-timeline-block -->';
               }
               html +='  </section> <!-- cd-timeline -->'+
                '</article>';
              $('#historiales-nav').empty();
              $('#historiales-nav').html(html);
              $('.scroll-pane').jScrollPane();
              console.log('listo'); */
          },
        });
    }
</script>
{% endblock %}

PortalAcraiz/templates/acraiz/dpc.html
 {% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}


{% block contenido %}


{% for proveedor in proveedores %}

  {% ifequal proveedor.publicar True %}
  <!--========== Otra sección ========-->
  <div class="container">
    <header class="clearfix">
      <h3 class="titulo_categoria">{{proveedor.nombre}}</h3>
    </header>

    <div class="caja">
    {% for autoridad in proveedor.autoridadescertificadoras_set.get_query_set %}
      {% ifequal autoridad.publicar True %}
        {% ifequal autoridad.publicar_dpc True %}
          <header class="clearfix">
            <h3 class="titulo_categoria">Declaración de Prácticas de Certificación</h3>
          </header>

          <h3 class="titulo-2">{{autoridad.nombre}}</h3>
          <div class="main container" style=" padding-bottom: 15px; border-bottom: 1px solid #DDD;">
            <ul id="rb-grid" class="rb-grid-dpc rb-grid clearfix">

              {% for dpc in autoridad.dpc_set.get_query_set %}        
                {% ifequal dpc.publicar True %}
                  <!--========== Otro Cuadro ========-->
                  <li >
                    <i class="fa fa-file-pdf-o icono-cuadro-princ"></i>
                    <h3> {{dpc.etiqueta}}</h3>
                    <a href="/media/{{ dpc.archivo }}" target="_blank">
                        <span class="rb-temp">Descargar</span>
                    </a>
                    <span class="pie_caption">
                      <p><a href="{{ dpc.huella }}" target="_blank">Huella SHA1</a></p>
                    </span>
                  </li> 
                {% endifequal %}
              {% endfor %}
            </ul>
          </div><!-- /.main-->
        {% endifequal %}        
      {% endifequal %}



        {% for certificado in autoridad.certificados_set.get_query_set %}
          {% ifequal certificado.ac.publicar True %}
            {% ifequal certificado.publicar True %}

          <header class="clearfix">
            <h3 class="titulo_categoria">Política de Certificado</h3>
          </header>

          <h3 class="titulo-2">{{ certificado.etiqueta}}</h3>
          <div class="main container" >
            <ul id="rb-grid" class="rb-grid-dpc rb-grid clearfix">

              {% for pc in certificado.pc_set.get_query_set %}
                {% ifequal pc.publicar True %}
                  <!--========== Otro Cuadro ========-->
                  <li >
                    <i class="fa fa-file-pdf-o icono-cuadro-princ"></i>
                    <h3>{{pc.etiqueta}}</h3>
                    <a href="/media/{{ pc.archivo }}" target="_blank"><span class="rb-temp">Descargar</span></a>
                    <span class="pie_caption">
                      <p><a href="{{ pc.huella }}" target="_blank">Huella SHA1</a></p>
                    </span>
                  </li> 
                {% endifequal %}
              {% endfor %}
            </ul>
          </div><!-- /.main-->
            {% endifequal %}
          {% endifequal %}
        {% endfor %}



    {% endfor %}


    </div>
    <br>
</div><!-- /.container -->
  {% endifequal %}

{% endfor %}


{% endblock %}

PortalAcraiz/templates/acraiz/lcr.html
{% extends "base.html" %}
{% load cms_tags %}
{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block contenido %}


{% for autoridad in autoridades %}
<!--========== Otra sección ========-->
<div class="container">
  {% ifequal autoridad.proveedor.publicar True %}
  {% ifequal autoridad.publicar True %}
    {% ifequal autoridad.lcr_set.get_query_set.first.publicar True %}
    <div class="caja">  
    <header class="clearfix">
      <h3 class="titulo_categoria" style=" padding-bottom: 5px; border-bottom: 1px solid #DDD;">{{ autoridad.nombre }}</h3>
    </header>

      <div class="main container">
        <ul id="rb-grid" class="rb-grid clearfix">
        <!--========== Otro Cuadro ========-->
               <li>
                  <i class="fa fa-cloud-download icono-cuadro-princ"></i>
                  <h3>{{ autoridad.lcr_set.get_query_set.first.ac }}</h3>
                  <span class="rb-temp">{{autoridad.lcr_set.get_query_set.first.hash_cert}}</span>
                  <div class="rb-overlay">
                    <span class="rb-close"><i class="fa fa-close"></i></span>
                    <div class="rb-week">
                      <div>
                        <span class="rb-city span-overbox-header">{{autoridad.lcr_set.get_query_set.first.ac}}</span>
                        <i class="span-overbox-icon fa fa-cloud-download"></i>
                        <span class="span-overbox-footer">{{autoridad.lcr_set.get_query_set.first.hash_cert}}</span>
                      </div>

              {% for formato in autoridad.lcr_set.get_query_set.first.formatolcr_set.get_query_set %}
                      <div class="span-columna">
                        <span class="descarga-formato">
                        <span class="header-colum-formato-overbox">{{ formato.formato }}</span>
                        <a href="/media/{{ formato.archivo }}" class="enlacelist" 
                          onclick="window.open(this.href, '', 'resizable=yes,status=no,location=no,toolbar=no,menubar=no,fullscreen=no,scrollbars=yes,dependent=no,width=700,height=500'); return false;">
                          <i class="fa fa-download fa-5x span-columna-icon"></i>
                        </a>
                        </span>
                        <a href="{{ formato.huella }}" class="enlacelist" 
                          onclick="window.open(this.href, '', 'resizable=yes,status=no,location=no,toolbar=no,menubar=no,fullscreen=no,scrollbars=yes,dependent=no,width=700,height=500'); return false;">
                          <span class="span-columna-footer">Huella SHA1</span>
                        </a>
                      </div>
                      {% endfor %}
                      </div>
                </li>
        </ul>
      </div><!-- /.main-->
      </div>
      <br>
    {% endifequal %}
  {% endifequal %}
  {% endifequal %}
</div><!-- /.container -->
{% endfor %}

{% endblock %}



{% block javascript %}

{% endblock %}

PortalAcraiz/templates/acraiz/ocsp.html
 {% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %} 
    <div id="interna"> <!-- InstanceBeginEditable name="contenido_segmentado" -->
      <div class="informativa">
        <div id="contenedorInformacion">
            <h1>{% page_attribute 'title' %}</h1>
        <section class="ac-container">
            <div>
                <input id="ac-1" name="accordion-1" type="radio" checked />
                <label for="ac-1">LDAP</label>
                <article class="ac-XXXlarge">

{% for var in ocspldap %}


{{var.archivo_ldap }}   

{% endfor %}








              </article>
              </div>
            <div>
                <input id="ac-2" name="accordion-1" type="radio" />
                <label for="ac-2">OCSP</label>
                <article class="ac-XXXlarge">
{{ ocspldap.archivo_ocsp }}
              </article>
              </div>         
          </section>
      </div></div>
      <!-- InstanceEndEditable --> </div>
{% endblock content %}